# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aricletype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='lifenote',
            name='praisecount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comment',
            name='Lifenote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylife.Lifenote'),
        ),
        migrations.AddField(
            model_name='lifenote',
            name='aricletype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mylife.Aricletype'),
            preserve_default=False,
        ),
    ]
