# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0003_auto_20170313_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Lifenote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylife.Lifenote'),
        ),
        migrations.AlterField(
            model_name='lifenote',
            name='praisecount',
            field=models.IntegerField(default=0),
        ),
    ]
