# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-18 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0005_auto_20170313_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Lifenote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylife.Lifenote'),
        ),
    ]
