# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 06:06
from __future__ import unicode_literals

import aboutme.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('introduce', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('avatar', models.ImageField(blank=True, upload_to=aboutme.models.get_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('introduce', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UseTechnial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_time', models.DateTimeField(auto_now=True)),
                ('myself', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.Myself')),
                ('technical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.Technical')),
            ],
        ),
    ]
