# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical',
            name='introduce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
