# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_auto_20170312_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usetechnial',
            name='user_time',
        ),
        migrations.AddField(
            model_name='usetechnial',
            name='usetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
