# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_auto_20170312_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myself',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
