# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-18 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0005_auto_20170312_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='myself',
            name='job_post',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myself',
            name='qq_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
