# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-18 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0006_auto_20170318_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='myself',
            name='education_background',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myself',
            name='university',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myself',
            name='work_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
